spring:
  application:
    name: j-ai-code-mothor-banckend
  profiles:
    active: local
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_ai_code_mother
    username: root
    password: root1234
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.jelly.jaicodemothor.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
